services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learninglabs
    volumes:
      - learninglabs_pg:/var/lib/postgresql/data

volumes:
  learninglabs_pg:
