import type { Metadata } from 'next';
import { Vazirmatn } from 'next/font/google';
import './globals.css';
import Footer from '@/section/footer/footer';
import Navbar from '@/section/nav/navbar';
import Providers from '@/components/theme/providers'
import Banner from '@/section/banner';

const vazir = Vazirmatn({ subsets: ['arabic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir='rtl' lang='fa-Ir' suppressHydrationWarning>
      <body className={vazir.className}>
      <Providers>
        <Navbar />
        <Banner banner={"images/https___s3-us-west-2.avif"} cover={"images/fikeus-west-2.avif"} /> 
        <div className='flex min-h-dvh flex-col justify-between'>
          {children}
          <Footer />
        </div>
        </Providers>
      </body>
    </html>
  );
}