import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/section/nav/navbar';
import { Vazirmatn } from 'next/font/google';
import Providers from '@/components/theme/providers'


const vazir = Vazirmatn({ subsets: ['arabic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fa-Ir' suppressHydrationWarning>
      <body className={`${vazir.className} bg-[#f8f8f8] dark:text-[hsla(0,0%,100%,.9)]  text-[#37352f] dark:bg-[#2f3437] `}>
      <Providers>
        <Navbar />
    
          {children}
       
        </Providers>
      </body>
    </html>
  );
}